version: '3'

services:
    application:
        image: nginx:alpine
        container_name: application

    sidecar:
        image: brendanburns/topz:db0fa58

        ports:
            - "8080:8080"

        pid: service:application
        command: /server --addr=0.0.0.0:8080
        depends_on:
            - application

